services:
  proxy_pool_api:
    build: .
    container_name: proxy_pool_api
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
    depends_on:
      - proxy_redis
    working_dir: /app
    restart: always
    command: uvicorn api.proxyApi:app --host 0.0.0.0 --port 5010

  proxy_pool_scheduer:
    build: .
    container_name: proxy_pool_scheduer
    links:
      - proxy_redis
    environment:
      PYTHONPATH: "/app"
      DB_CONN: "redis://@proxy_redis:6379/0"
    depends_on:
      - proxy_redis
    working_dir: /app
    restart: always
    command: python helper/scheduler.py

  proxy_redis:
    image: "redis"
    container_name: proxy_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: always
